id: A534FA92F
title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
type: translation
pechas:
- IEB9656F8
- I04B2D54D
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-002
  eft-text-version: 1.3.4 2020
  title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
alignment_to_base:
  IEB9656F8/19F5: '1519'
  I04B2D54D/D2BF: '1519'
